# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Solution building Python libraries.

package(default_visibility = [
    "//intrinsic/solutions:__subpackages__",
    "//intrinsic_sdk/intrinsic/solutions:__subpackages__",
])

alias(
    name = "process_providing",
    actual = "//intrinsic_sdk/intrinsic/solutions/internal:process_providing",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "actions",
    actual = "//intrinsic_sdk/intrinsic/solutions/internal:actions",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "code_execution",
    actual = "//intrinsic_sdk/intrinsic/solutions/internal:code_execution",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "code_execution_client",
    actual = "//intrinsic_sdk/intrinsic/solutions/internal:code_execution_client",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "blackboard",
    actual = "//intrinsic_sdk/intrinsic/solutions/internal:blackboard",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "resources",
    actual = "//intrinsic_sdk/intrinsic/solutions/internal:resources",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "skill_utils",
    actual = "//intrinsic_sdk/intrinsic/solutions/internal:skill_utils",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "skill_providing",
    actual = "//intrinsic_sdk/intrinsic/solutions/internal:skill_providing",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = [
        "//intrinsic/solutions:__subpackages__",
        "//intrinsic_sdk/intrinsic/solutions:__subpackages__",
    ],
)

alias(
    name = "stubs",
    actual = "//intrinsic_sdk/intrinsic/solutions/internal:stubs",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)
