# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Helper utilities for applications using grpc."""

package(
    default_visibility = ["//visibility:public"],
)

alias(
    name = "channel_interface",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:channel_interface",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "auth_py",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:auth_py",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "dialerutil",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:dialerutil",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "channel",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:channel",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "connection_params",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:connection_params",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "connection_cache",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:connection_cache",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "connection",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:connection",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "grpc",
    actual = "//intrinsic_sdk/intrinsic/util/grpc",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = ["//intrinsic:public_api_users"],
)

alias(
    name = "limits",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:limits",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = ["//intrinsic:public_api_users"],
)

alias(
    name = "interceptor",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:interceptor",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "error_handling",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:error_handling",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "statusutil",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:statusutil",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "userconfig",
    actual = "//intrinsic_sdk/intrinsic/util/grpc:userconfig",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)
