# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

alias(
    name = "motion_planner_service_migration_go_proto",
    actual = "//intrinsic_sdk/intrinsic/solution_versions/proto/v1alpha1:motion_planner_service_migration_go_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = [
        "//intrinsic/solution_versions:__subpackages__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/solution/migrate:__pkg__",
    ],
)

alias(
    name = "solution_migration_go_proto",
    actual = "//intrinsic_sdk/intrinsic/solution_versions/proto/v1alpha1:solution_migration_go_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = [
        "//intrinsic/solution_versions:__subpackages__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/solution/migrate:__pkg__",
    ],
)
