# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//bazel:go_macros.bzl", "go_proto_library")
load("//bazel:protos.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "skill_runtime_proto",
    srcs = ["skill_runtime.proto"],
    deps = [":skill_registry_config_proto"],
)

go_proto_library(
    name = "skill_runtime_go_proto",
    importpath = "intrinsic/skills/proto/skill_runtime_go_proto",
    protos = [":skill_runtime_proto"],
    deps = [
        ":skill_registry_config_go_proto",
    ],
)

alias(
    name = "behavior_tree_registry_py_pb2",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:behavior_tree_registry_py_pb2",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "behavior_tree_registry_py_pb2_grpc",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:behavior_tree_registry_py_pb2_grpc",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "behavior_tree_registry_go_proto",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:behavior_tree_registry_go_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "skill_service_proto",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:skill_service_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "skill_service_cc_proto",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:skill_service_cc_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "skill_service_cc_grpc_proto",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:skill_service_cc_grpc_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "skill_service_go_proto",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:skill_service_go_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "skill_registry_config_proto",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:skill_registry_config_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "skill_registry_config_py_pb2",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:skill_registry_config_py_pb2",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "skill_registry_config_go_proto",
    actual = "//intrinsic_sdk/intrinsic/skills/proto:skill_registry_config_go_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)
