# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Testing utilities for skills.

package(
    default_testonly = True,
)

alias(
    name = "skill_test_utils",
    actual = "//intrinsic_sdk/intrinsic/skills/testing:skill_test_utils",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = [
        "//intrinsic:public_api_users",
    ],
)

alias(
    name = "skill_test_utils_cc",
    actual = "//intrinsic_sdk/intrinsic/skills/testing:skill_test_utils_cc",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = [
        "//intrinsic:public_api_users",
    ],
)
