# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(default_visibility = ["//intrinsic:public_api_users"])

alias(
    name = "processfix",
    actual = "//intrinsic_sdk/intrinsic/assets/processes:processfix",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = ["//intrinsic:internal_api_users"],
)

alias(
    name = "processmanifest",
    actual = "//intrinsic_sdk/intrinsic/assets/processes:processmanifest",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "processvalidate",
    actual = "//intrinsic_sdk/intrinsic/assets/processes:processvalidate",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)
