# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(default_visibility = ["//visibility:public"])

alias(
    name = "log_dispatcher_service_cc_proto",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:log_dispatcher_service_cc_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "log_dispatcher_service_go_proto",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:log_dispatcher_service_go_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "log_item_proto",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:log_item_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "log_item_cc_proto",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:log_item_cc_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "log_item_go_proto",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:log_item_go_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "log_item_py_pb2",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:log_item_py_pb2",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "logger_service_cc_proto",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:logger_service_cc_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "logger_service_cc_grpc",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:logger_service_cc_grpc",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "logger_service_go_proto",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:logger_service_go_proto",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "logger_service_py_pb2",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:logger_service_py_pb2",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "logger_service_py_pb2_grpc",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:logger_service_py_pb2_grpc",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "recording_data_categories_go",
    actual = "//intrinsic_sdk/intrinsic/logging/proto:recording_data_categories_go",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = ["//visibility:public"],
)
