# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(default_visibility = ["//visibility:public"])

alias(
    name = "cmd",
    actual = "//intrinsic_sdk/intrinsic/skills/tools/skill/cmd",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "solutionutil",
    actual = "//intrinsic_sdk/intrinsic/skills/tools/skill/cmd:solutionutil",
    tags = ["go/intrinsic-ioc-transition-tdd"],
)

alias(
    name = "dialerutil",
    actual = "//intrinsic_sdk/intrinsic/skills/tools/skill/cmd:dialerutil",
    tags = ["go/intrinsic-ioc-transition-tdd"],
    visibility = [
        "//intrinsic/skills/tools/skill/cmd:__pkg__",
        "//intrinsic/storage/artifacts/client:__pkg__",
        "//intrinsic/tools/inctl/cmd:__pkg__",
        "//intrinsic/tools/inctl/cmd/cluster:__pkg__",
        "//intrinsic/tools/inctl/cmd/logs:__pkg__",
        "//intrinsic_sdk/intrinsic/skills/tools/skill/cmd:__pkg__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd:__pkg__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/cluster:__pkg__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/device:__pkg__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/logs:__pkg__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/process:__pkg__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/solution:__pkg__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/solution/get:__pkg__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/solution/start:__pkg__",
        "//intrinsic_sdk/intrinsic/tools/inctl/cmd/solution/stop:__pkg__",
    ],
)
